# Render Blueprint: Backend (Django) + Frontend (Vite Static)
services:
  - type: web
    name: controle-producao-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate --noinput
    startCommand: gunicorn backend_project.wsgi:application --chdir backend --log-file -
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      # Opcional: se usar Postgres no Render, crie um database e conecte aqui
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: controle-producao-db
      #     property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1,controlesetup.com.br,www.controlesetup.com.br"
      - key: FRONTEND_ORIGINS
        value: "https://controle-producao-frontend.onrender.com,https://www.controlesetup.com.br"

  - type: static
    name: controle-producao-frontend
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    publishPath: frontend/dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE
        value: "https://controle-producao-backend.onrender.com/api"
