# Generated by Django 5.2.3 on 2025-08-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pep', models.CharField(db_index=True, max_length=64)),
                ('prazo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_conclusao', models.DateField(blank=True, db_index=True, null=True)),
                ('mes', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('status_sap', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('seccional', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status_ener', models.CharField(blank=True, max_length=128, null=True)),
                ('status_conc', models.CharField(blank=True, max_length=128, null=True)),
                ('status_servico', models.CharField(blank=True, max_length=128, null=True)),
                ('fonte', models.CharField(default='sheets', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matriz - Linha',
                'verbose_name_plural': 'Matriz - Linhas',
                'indexes': [models.Index(fields=['seccional'], name='dados_matri_seccion_1cce0b_idx'), models.Index(fields=['status_sap'], name='dados_matri_status__ccf87f_idx'), models.Index(fields=['tipo'], name='dados_matri_tipo_c8e12f_idx'), models.Index(fields=['mes'], name='dados_matri_mes_188b1f_idx')],
            },
        ),
    ]
