# Generated by Django 5.2.3 on 2025-09-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    # Esta migration foi convertida em no-op para evitar inconsistência de estado
    # durante a reconstrução (KeyError ao remover modelo ausente). O modelo
    # MatrizRow não é mais utilizado.
    operations = []
