# Generated by Django 5.2.3 on 2025-09-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatrizRow',
        ),
    ]
